security:
    encoders:
        RFC\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_MANAGER:   ROLE_USER
        ROLE_CERTIFIED_MANAGER:   [ROLE_USER, ROLE_MANAGER]
        ROLE_ADMIN: [ROLE_CERTIFIED_MANAGER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key: %secret%

    access_control:
    # app/config/security.yml

    access_control:
        - { path: ^/admin, roles: ROLE_MANAGER }
