rfcCore_accueil:
    path:   /
    defaults: { _controller: RFCCoreBundle:Core:index }
rfcCore_gameSelection:
    path:   /{gameId}/
    defaults: { _controller: RFCCoreBundle:Core:accessGame }
    requirements:
        gameId: \d*
rfcCore_admin_index:
    path:   /admin/
    defaults: { _controller: RFCCoreBundle:Admin:index }
rfcCore_admin_addGame:
    path:   /admin/addGame
    defaults: { _controller: RFCCoreBundle:Admin:addGame }
RFCCoreBundle_admin_game:
    resource: "@RFCCoreBundle/Resources/config/routing/game.yml"
    prefix:   /admin/game