rfcCore_accueil:
    path:   /
    defaults: { _controller: "RFCCoreBundle:Core:index" } 
    
rfcCore_gameSelection:
    path:   /{gameId}/
    defaults: { _controller: "RFCCoreBundle:Core:accessGame" } 
    requirements:
        gameId: \d*
    options:
        expose: true
    
rfcCore_showGallery:
    path:   /showGallery/{elementType}_{elementId}
    defaults: { _controller: "RFCCoreBundle:Core:showGallery" }

rfcCore_calendar:
    path:   /{gameId}/Calendar
    defaults: { _controller: "RFCCoreBundle:Calendar:index" }
    requirements:
        gameId: \d*

rfcCore_user:
    path:   /User
    defaults: { _controller: "RFCCoreBundle:User:index" }
    
rfcCore_user_update:
    pattern:  /User/update
    defaults: { _controller: "RFCCoreBundle:User:update" }
    requirements: { _method: post|put }

rfcCore_crew:
    path:   /{gameId}/Crew
    defaults: { _controller: "RFCCoreBundle:Crew:index" }
    requirements:
        gameId: \d*

rfcCore_members:
    path:   /{gameId}/Members
    defaults: { _controller: "RFCCoreBundle:Members:index" }
    requirements:
        gameId: \d*

rfcCore_members_show:
    path:   /{gameId}/Members/{userId}
    defaults: { _controller: "RFCCoreBundle:Members:show" }
    requirements:
        gameId: \d*
        userId: \d*
        
rfcCore_championships:
    path:   /{gameId}/Championships
    defaults: { _controller: "RFCCoreBundle:Championship:index" }
    requirements:
        gameId: \d*
        
rfcCore_championships_show:
    path:   /{gameId}/Championship_{championshipId}/
    defaults: { _controller: "RFCCoreBundle:Championship:show" }
    requirements:
        gameId: \d*
        championshipId: \d*

RFCAjax:
     resource: "@RFCCoreBundle/Resources/config/routing/ajax.yml"
     prefix:   /