rfcCore_accueil:
    path:   /
    defaults: { _controller: "RFCCoreBundle:Core:index" }
    
rfcCore_systemParameters:
    path:   /systemParameters
    defaults: { _controller: "RFCCoreBundle:Core:systemParameters" }
    
rfcCore_gameParameters:
    path:   /{gameId}/parameters
    defaults: { _controller: "RFCCoreBundle:Core:gameParameters" }
    
rfcCore_gameSelection:
    path:   /{gameId}/
    defaults: { _controller: "RFCCoreBundle:Core:accessGame" } 
    requirements:
        gameId: \d*
    options:
        expose: true
    
rfcCore_manageGallery:
    path:   /gallery/{entityType}_{entityId}
    defaults: { _controller: "RFCCoreBundle:Gallery:manage" }

rfcCore_calendar:
    path:   /{gameId}/Calendar
    defaults: { _controller: "RFCCoreBundle:Calendar:index" }
    requirements:
        gameId: \d*

rfcCore_user:
    path:   /User
    defaults: { _controller: "RFCCoreBundle:User:index" }
    
rfcCore_user_update:
    pattern:  /User/update
    defaults: { _controller: "RFCCoreBundle:User:update" }
    requirements: { _method: post|put }

rfcCore_crew:
    path:   /{gameId}/Crew
    defaults: { _controller: "RFCCoreBundle:Crew:index" }
    requirements:
        gameId: \d*

rfcCore_members:
    path:   /Members
    defaults: { _controller: "RFCCoreBundle:Members:index" }

rfcCore_members_show:
    path:   /Members/{userId}
    defaults: { _controller: "RFCCoreBundle:Members:show" }
    requirements:
        userId: \d*

rfcCore_members_edit:
    path:   /Members/{userId}/edit
    defaults: { _controller: "RFCCoreBundle:Members:edit" }
    requirements:
        userId: \d*
        
rfcCore_championships:
    path:   /{gameId}/Championship
    defaults: { _controller: "RFCCoreBundle:Championship:index" }
    requirements:
        gameId: \d*
        
rfcCore_championships_show:
    path:   /{gameId}/Championship/{championshipId}
    defaults: { _controller: "RFCCoreBundle:Championship:show" }
    requirements:
        gameId: \d*
        championshipId: \d*

RFCAjax:
     resource: "@RFCCoreBundle/Resources/config/routing/ajax.yml"
     prefix:   /
     
RFCApi:
     resource: "@RFCCoreBundle/Resources/config/routing/api.yml"
     prefix:   /
     