rfcCore_accueil:
    path:   /
    defaults: { _controller: RFCCoreBundle:Core:index }
rfcCore_gameSelection:
    path:   /{gameId}/
    defaults: { _controller: RFCCoreBundle:Core:accessGame }
    requirements:
        gameId: \d*
rfcCore_admin_index:
    path:   /admin/
    defaults: { _controller: RFCCoreBundle:Admin:index }
rfcCore_admin_addGame:
    path:   /admin/addGame
    defaults: { _controller: RFCCoreBundle:Admin:addGame }
RFCCoreBundle_admin_game:
    resource: "@RFCCoreBundle/Resources/config/routing/game.yml"
    prefix:   /admin/game
RFCCoreBundle_admin_rule:
     resource: "@RFCCoreBundle/Resources/config/routing/rule.yml"
     prefix:   /admin/rule
RFCCoreBundle_admin_championship:
    resource: "@RFCCoreBundle/Resources/config/routing/championship.yml"
    prefix:   /admin/championship
RFCCoreBundle_admin_event:
    resource: "@RFCCoreBundle/Resources/config/routing/event.yml"
    prefix:   /admin/event
RFCCoreBundle_admin_session:
    resource: "@RFCCoreBundle/Resources/config/routing/session.yml"
    prefix:   /admin/session
RFCCoreBundle_admin_result:
    resource: "@RFCCoreBundle/Resources/config/routing/result.yml"
    prefix:   /admin/result
RFCCoreBundle_admin_track:
    resource: "@RFCCoreBundle/Resources/config/routing/track.yml"
    prefix:   /admin/track
RFCCoreBundle_admin_vehicle:
    resource: "@RFCCoreBundle/Resources/config/routing/vehicle.yml"
    prefix:   /admin/vehicle
RFCCoreBundle_admin_category:
    resource: "@RFCCoreBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category
RFCCoreBundle_admin_metaRule:
    resource: "@RFCCoreBundle/Resources/config/routing/metarule.yml"
    prefix:   /admin/metaRule