rfcCore_accueil:
    path:   /
    defaults: { _controller: RFCCoreBundle:Core:index }
rfcCore_gameSelection:
    path:   /{gameId}/
    defaults: { _controller: RFCCoreBundle:Core:accessGame }
    requirements:
        gameId: \d*