parameters:
#    rfc_setup.example.class: RFC\SetupBundle\Example

services:
#    rfc_setup.example:
#        class: %rfc_setup.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
