<?php

namespace RFC\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetaRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaRuleRepository extends EntityRepository
{
}
