<?php
namespace RFC\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends EntityRepository
{

    public function getForMetaRule($metaRuleId)
    {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.listMetaRules', 'm')
            ->where('m.id = :metaRuleId')
            ->setParameter('metaRuleId', $metaRuleId)
            ->getQuery()
            ->getResult();
    }
}
