parameters:
#    rfc_user.example.class: RFC\UserBundle\Example

services:
#    rfc_user.example:
#        class: %rfc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
