ajax_user_register_championship:
    pattern: /userRegisterChampionship
    defaults: { _controller: "RFCCoreBundle:Championship:userRegistration" }
    requirements: { _method: post }
    options:
        expose: true
        
ajax_properties_update:
    pattern: /updateProperties}
    defaults: { _controller: "RFCAdminBundle:System:updateProperties" }
    requirements: { _method: post }
    options:
        expose: true