ajax_user_register_championship:
    pattern: /userRegisterChampionship
    defaults: { _controller: "RFCCoreBundle:Championship:userRegistration" }
    requirements: { _method: post }
    options:
        expose: true
        
ajax_properties_update:
    pattern: /updateProperties
    defaults: { _controller: "RFCAdminBundle:System:updateProperties" }
    requirements: { _method: post }
    options:
        expose: true
        
ajax_crew_application:
    pattern: /crewApplication
    defaults: { _controller: "RFCCoreBundle:Crew:crewApplication" }
    requirements: { _method: post }
    options:
        expose: true

ajax_crew_retire:
    pattern: /crewRetirement
    defaults: { _controller: "RFCCoreBundle:Crew:crewRetirement" }
    requirements: { _method: post }
    options:
        expose: true
        
ajax_crew_accept:
    pattern: /crewAccept
    defaults: { _controller: "RFCCoreBundle:Crew:crewAccept" }
    requirements: { _method: post }
    options:
        expose: true

ajax_championship_getResults:
    pattern: /getChampionshipResults
    defaults: { _controller: "RFCCoreBundle:Championship:getResults" }
    requirements: { _method: post }
    options:
        expose: true