ajax_user_register_team:
    pattern: /team/{teamid}/register/{drivertype}/{driverid}
    defaults: { _controller: "RFCCoreBundle:Championship:userRegisterTeam" }
    requirements: { _method: post }
    options:
        expose: true
        
ajax_user_unregister_team:
    pattern: /team/{teamid}/unregister/{drivertype}/{driverid}
    defaults: { _controller: "RFCCoreBundle:Championship:userUnregisterTeam" }
    requirements: { _method: post }
    options:
        expose: true

ajax_registration:
    pattern: /championship/{championshipid}/{driverid}/{registeraction}/{drivertype}/{teamid}
    defaults: { _controller: "RFCCoreBundle:Championship:registration", drivertype: 1, teamid: null }
    requirements:
        _method: post
        championshipid: \d+
        driverid: \d+
        registeraction: register|unregister
        drivertype: 1|2
        teamid: -?\d+
    options:
        expose: true

ajax_vehicle_selection:
    pattern: /registration/{registrationid}/{vehicleid}/{registeraction}
    defaults: { _controller: "RFCCoreBundle:Championship:vehicleSelection" }
    requirements:
        _method: post
        registrationid: \d+
        vehicleid: \d+
        registeraction: register|unregister