admin_metaRule:
    pattern:  /
    defaults: { _controller: "RFCCoreBundle:MetaRule:index" }

admin_metaRule_show:
    pattern:  /{id}/show
    defaults: { _controller: "RFCCoreBundle:MetaRule:show" }

admin_metaRule_new:
    pattern:  /new
    defaults: { _controller: "RFCCoreBundle:MetaRule:new" }

admin_metaRule_create:
    pattern:  /create
    defaults: { _controller: "RFCCoreBundle:MetaRule:create" }
    requirements: { _method: post }

admin_metaRule_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RFCCoreBundle:MetaRule:edit" }

admin_metaRule_update:
    pattern:  /{id}/update
    defaults: { _controller: "RFCCoreBundle:MetaRule:update" }
    requirements: { _method: post|put }

admin_metaRule_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RFCCoreBundle:MetaRule:delete" }
    requirements: { _method: post|delete }
