admin_session_search:
    pattern: /searchSession
    defaults: { _controller: "RFCAdminBundle:Session:search" }
    requirements: { _method: post }
    options:
        expose: true
admin_rule_search:
    pattern: /searchRule
    defaults: { _controller: "RFCAdminBundle:Rule:search" }
    requirements: { _method: post }
    options:
        expose: true
        
ajax_session_load:
    pattern: /sessionLoad
    defaults: { _controller: "RFCAdminBundle:Session:sessionLoad" }
    requirements: { _method: post }
    options:
        expose: true  