admin_category:
    pattern:  /
    defaults: { _controller: "RFCAdminBundle:Category:index" }

admin_category_show:
    pattern:  /{categoryId}/show
    defaults: { _controller: "RFCAdminBundle:Category:show" }

admin_category_new:
    pattern:  /new
    defaults: { _controller: "RFCAdminBundle:Category:new" }

admin_category_create:
    pattern:  /create
    defaults: { _controller: "RFCAdminBundle:Category:create" }
    requirements: { _method: post }

admin_category_edit:
    pattern:  /{categoryId}/edit
    defaults: { _controller: "RFCAdminBundle:Category:edit" }

admin_category_update:
    pattern:  /{categoryId}/update
    defaults: { _controller: "RFCAdminBundle:Category:update" }
    requirements: { _method: post|put }

admin_category_delete:
    pattern:  /{categoryId}/delete
    defaults: { _controller: "RFCAdminBundle:Category:delete" }
    requirements: { _method: post|delete }
