admin_metaRule:
    pattern:  /
    defaults: { _controller: "RFCAdminBundle:MetaRule:index" }

admin_metaRule_show:
    pattern:  /{metaRuleId}/show
    defaults: { _controller: "RFCAdminBundle:MetaRule:show" }

admin_metaRule_new:
    pattern:  /new
    defaults: { _controller: "RFCAdminBundle:MetaRule:new" }

admin_metaRule_create:
    pattern:  /create
    defaults: { _controller: "RFCAdminBundle:MetaRule:create" }
    requirements: { _method: post }

admin_metaRule_edit:
    pattern:  /{metaRuleId}/edit
    defaults: { _controller: "RFCAdminBundle:MetaRule:edit" }

admin_metaRule_update:
    pattern:  /{metaRuleId}/update
    defaults: { _controller: "RFCAdminBundle:MetaRule:update" }
    requirements: { _method: post|put }

admin_metaRule_delete:
    pattern:  /{metaRuleId}/delete
    defaults: { _controller: "RFCAdminBundle:MetaRule:delete" }
    requirements: { _method: post|delete }
