admin_rule:
    pattern:  /
    defaults: { _controller: "RFCAdminBundle:Rule:index" }

admin_rule_show:
    pattern:  /{ruleId}/show
    defaults: { _controller: "RFCAdminBundle:Rule:show" }

admin_rule_new:
    pattern:  /new
    defaults: { _controller: "RFCAdminBundle:Rule:new" }

admin_rule_create:
    pattern:  /create
    defaults: { _controller: "RFCAdminBundle:Rule:create" }
    requirements: { _method: post }

admin_rule_edit:
    pattern:  /{ruleId}/edit
    defaults: { _controller: "RFCAdminBundle:Rule:edit" }

admin_rule_update:
    pattern:  /{ruleId}/update
    defaults: { _controller: "RFCAdminBundle:Rule:update" }
    requirements: { _method: post|put }

admin_rule_delete:
    pattern:  /{ruleId}/delete
    defaults: { _controller: "RFCAdminBundle:Rule:delete" }
    requirements: { _method: get|post|delete }
