admin_session:
    pattern:  /
    defaults: { _controller: "RFCAdminBundle:Session:index" }

admin_session_show:
    pattern:  /{id}/show
    defaults: { _controller: "RFCAdminBundle:Session:show" }

admin_session_new:
    pattern:  /new
    defaults: { _controller: "RFCAdminBundle:Session:new" }

admin_session_create:
    pattern:  /create
    defaults: { _controller: "RFCAdminBundle:Session:create" }
    requirements: { _method: post }

admin_session_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "RFCAdminBundle:Session:edit" }

admin_session_update:
    pattern:  /{id}/update
    defaults: { _controller: "RFCAdminBundle:Session:update" }
    requirements: { _method: post|put }

admin_session_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "RFCAdminBundle:Session:delete" }
    requirements: { _method: post|delete }
