<?php
/*
 * //RF//Championship is a multi-racing game team manager that allows members to organize and follow championships.
 * Copyright (C) 2014 - //Racing-France//
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
namespace RFC\SetupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SetupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends EntityRepository {

    /**
     * Returns the max step order query for a game.
     * @param type $gameId
     */
    public function queryLastStepId($gameId) {
        $query = $this->createQueryBuilder('s')
            ->select('s.stepOrder')
            ->where('s.game = :gameId')
            ->setParameter('gameId', $gameId)
            ->setMaxResults(1)
            ->orderBy('s.stepOrder', 'DESC');

        return $query;
    }

    /**
     * Returns the result of the LastStep query
     * @param type $gameId
     * @return type
     */
    public function findLastStepId($gameId) {
        return $this->queryLastStepId($gameId)
            ->getQuery()
            ->getOneOrNullResult();
    }
    
}
