RFCAdmin_index:
    path:   /admin/
    defaults: { _controller: RFCAdminBundle:Admin:index }
RFCAdmin_user:
    resource: "@RFCAdminBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user
RFCAdmin_game:
    resource: "@RFCAdminBundle/Resources/config/routing/game.yml"
    prefix:   /admin/game
RFCAdmin_system:
    resource: "@RFCAdminBundle/Resources/config/routing/system.yml"
    prefix:   /admin/system
RFCAdmin_championship:
    resource: "@RFCAdminBundle/Resources/config/routing/championship.yml"
    prefix:   /admin/game/{gameId}/championship
RFCAdmin_event:
    resource: "@RFCAdminBundle/Resources/config/routing/event.yml"
    prefix:   /admin/game/{gameId}/championship/{championshipId}/event
RFCAdmin_session:
    resource: "@RFCAdminBundle/Resources/config/routing/session.yml"
    prefix:   /admin/game/{gameId}/championship/{championshipId}/event/{eventId}/session
RFCAdmin_result:
    resource: "@RFCAdminBundle/Resources/config/routing/result.yml"
    prefix:   /admin/result
RFCAdmin_track:
    resource: "@RFCAdminBundle/Resources/config/routing/track.yml"
    prefix:   /admin/game/{gameId}/track
RFCAdmin_vehicle:
    resource: "@RFCAdminBundle/Resources/config/routing/vehicle.yml"
    prefix:   /admin/game/{gameId}/vehicle
RFCAdmin_category:
    resource: "@RFCAdminBundle/Resources/config/routing/category.yml"
    prefix:   /admin/game/{gameId}/category
RFCAdmin_metaRule:
    resource: "@RFCAdminBundle/Resources/config/routing/metarule.yml"
    prefix:   /admin/game/{gameId}/metaRule
RFCAdmin_rule:
     resource: "@RFCAdminBundle/Resources/config/routing/rule.yml"
     prefix:   /admin/game/{gameId}/rule
RFCAdmin_typeSession:
     resource: "@RFCAdminBundle/Resources/config/routing/typeSession.yml"
     prefix:   /admin/game/{gameId}/typeSession
RFCAjax:
     resource: "@RFCAdminBundle/Resources/config/routing/ajax.yml"
     prefix:   /