parameters:
#    rfc_admin.example.class: RFC\AdminBundle\Example

services:
#    rfc_admin.example:
#        class: %rfc_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
