-- This script completely redesigns the car setup feature.
-- It is intended to be run on a database where the old setup tables might exist.

-- Drop old setup-related objects to ensure a clean slate.
DROP TABLE IF EXISTS public.setups CASCADE;
DROP TABLE IF EXISTS public.setup_values CASCADE;
DROP TABLE IF EXISTS public.setup_parameters CASCADE;
DROP TABLE IF EXISTS public.parameter_rules CASCADE;
DROP FUNCTION IF EXISTS get_setup_history(bigint);

-- Create new tables for the advanced setup system

CREATE TABLE public.setup_parameters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id bigint REFERENCES public.games(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    category text,
    value_type text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.parameter_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_id bigint NOT NULL REFERENCES public.setup_parameters(id) ON DELETE CASCADE,
    game_id bigint REFERENCES public.games(id) ON DELETE CASCADE,
    vehicle_id bigint REFERENCES public.vehicles(id) ON DELETE CASCADE,
    track_id bigint REFERENCES public.tracks(id) ON DELETE CASCADE,
    rule_id bigint REFERENCES public.rules(id) ON DELETE CASCADE,
    min_value float,
    max_value float,
    step_increment float,
    options text[],
    default_value text,
    is_locked boolean NOT NULL DEFAULT false,
    dependencies jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.setups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    vehicle_id bigint REFERENCES public.vehicles(id) ON DELETE CASCADE,
    track_id bigint REFERENCES public.tracks(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    version integer NOT NULL DEFAULT 1,
    parent_setup_id bigint REFERENCES public.setups(id) ON DELETE SET NULL,
    is_public boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.setup_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setup_id bigint NOT NULL REFERENCES public.setups(id) ON DELETE CASCADE,
    parameter_id bigint NOT NULL REFERENCES public.setup_parameters(id) ON DELETE CASCADE,
    value text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(setup_id, parameter_id)
);

-- Enable RLS
ALTER TABLE public.setups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.setup_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parameter_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.setup_values ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow users to view their own or public setups" ON public.setups FOR SELECT USING (auth.uid() = user_id OR is_public = true);
CREATE POLICY "Allow users to manage their own setups" ON public.setups FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Allow authenticated users to view setup parameters" ON public.setup_parameters FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to view parameter rules" ON public.parameter_rules FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow users to manage values for their own setups" ON public.setup_values USING ((SELECT user_id FROM public.setups WHERE id = setup_id) = auth.uid());
CREATE POLICY "Allow admin full access on setups" ON public.setups FOR ALL USING ((SELECT 'ROLE_ADMIN' = ANY(roles) FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow admin full access on setup_parameters" ON public.setup_parameters FOR ALL USING ((SELECT 'ROLE_ADMIN' = ANY(roles) FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow admin full access on parameter_rules" ON public.parameter_rules FOR ALL USING ((SELECT 'ROLE_ADMIN' = ANY(roles) FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow admin full access on setup_values" ON public.setup_values FOR ALL USING ((SELECT 'ROLE_ADMIN' = ANY(roles) FROM public.profiles WHERE id = auth.uid()));
